from fastapi import APIRouter, Depends, HTTPException, status, Response, Request
from pydantic import BaseModel
import asyncpg
from typing import Optional

from db.connect import get_db, create_tables
from core.security import verify_password, get_password_hash, create_access_token

router = APIRouter(prefix="/auth", tags=["auth"])

class UserCreate(BaseModel):
    username: str
    password: str

class UserLogin(BaseModel):
    username: str
    password: str

@router.post("/register")
async def register_user(user: UserCreate, db: asyncpg.Pool = Depends(get_db)):
    if not user.username or not user.password:
         raise HTTPException(status_code=400, detail="Username and password are required")
    
    hashed_password = get_password_hash(user.password)
    
    try:
        async with db.acquire() as conn:
            # Check if user exists
            existing = await conn.fetchval("SELECT id FROM users WHERE username = $1", user.username)
            if existing:
                raise HTTPException(status_code=400, detail="Username already registered")
            
            # Insert user. Assuming users.id is UUID or automatically generated by Postgres.
            user_id = await conn.fetchval(
                "INSERT INTO users (username, hashed_password) VALUES ($1, $2) RETURNING id",
                user.username, hashed_password
            )
            
            # Generate JWT Token 
            access_token = create_access_token(data={"sub": str(user_id)})
            
            return {"user_id": str(user_id), "access_token": access_token, "token_type": "bearer"}

    except asyncpg.PostgresError as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/login")
async def login_for_access_token(
    response: Response,
    user_data: UserLogin, 
    db: asyncpg.Pool = Depends(get_db)
):
    async with db.acquire() as conn:
        user = await conn.fetchrow("SELECT id, hashed_password FROM users WHERE username = $1", user_data.username)
        
    if not user or not verify_password(user_data.password, user['hashed_password']):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    access_token = create_access_token(data={"sub": str(user['id'])})
    
    # 1. Provide HttpOnly Cookie for Next.js Web App
    response.set_cookie(
        key="access_token",
        value=f"Bearer {access_token}",
        httponly=True,
        max_age=604800,  # 7 days
        expires=604800,
        samesite="lax",
        secure=False  # Set to False because we are entirely offline/localhost without HTTPS
    )
    
    # 2. Provide JSON Bearer token for Flutter Mobile App
    return {"access_token": access_token, "token_type": "bearer", "user_id": str(user['id'])}

@router.post("/logout")
async def logout(response: Response):
    response.delete_cookie("access_token")
    return {"message": "Logged out successfully"}
